
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape cAdvisor (container metrics)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
